# Generated by Django 5.0.6 on 2024-09-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_stops_alter_schedule_arrival_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='bus',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='departure_time',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
