# Generated by Django 5.0.6 on 2024-09-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_schedule_bus_alter_schedule_arrival_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='stops',
        ),
        migrations.AddField(
            model_name='schedule',
            name='stops',
            field=models.ManyToManyField(to='schedule.stop'),
        ),
    ]
