# Generated by Django 5.0.6 on 2024-09-29 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_schedule_stops_schedule_stops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='name',
        ),
    ]
