# Generated by Django 5.0.6 on 2024-09-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_remove_stop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='name',
        ),
        migrations.AddField(
            model_name='route',
            name='number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
